In [7]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel
from transformers import TFGPT2LMHeadModel

In [8]:
tokenizer=GPT2Tokenizer.from_pretrained('gpt2-large')

In [10]:
model=TFGPT2LMHeadModel.from_pretrained('gpt2-large',pad_token_id=tokenizer.eos_token_id)

All PyTorch model weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [11]:
tokenizer.eos_token_id

50256

# Encoding

In [16]:
sentence='Once there was a boy'
numeric_ids=tokenizer.encode(sentence,return_tensors='tf')
print(numeric_ids)

tf.Tensor([[7454  612  373  257 2933]], shape=(1, 5), dtype=int32)


In [22]:
tokenizer.decode(numeric_ids[0][2])

' was'

In [ ]:
Model G

In [23]:
result=model.generate(numeric_ids,max_length=100,num_beams=5,no_repeat_ngram_size=2,early_stopping=True)

In [24]:
result

<tf.Tensor: shape=(1, 100), dtype=int32, numpy=
array([[ 7454,   612,   373,   257,  2933,   290,   257,  2576,    11,
          290,   484,   547,   287,   262,   976,  2119,    11,   262,
         2933,   531,   284,   262,  2576,    25,   366,    40,  1101,
         1016,   284,  1494,   345,   526,   383,  2576,   531,    11,
          366,  2949,    11,   314,   836,   470,   765,   284,  4656,
           13,   314,   765,   345,   284,  2652,   351,   502,   526,
          198,   198,   464,  2933,  1718,   257,  9845,   422,   465,
        10000,   290, 21512,   607,    13,  1375,  3724,   287,   465,
         5101,    13,   383,  2933,   373,  5169,   290,  5047,   351,
          717,    12, 16863,  5123,    13,   679,   373, 11897,   284,
         1204,   287,  3770,  1231,   262,  5885,   286, 25450,    13,
        50256]])>

In [25]:
output_text=tokenizer.decode(result[0],skip_special_tokens=True)
print(output_text)

Once there was a boy and a girl, and they were in the same room, the boy said to the girl: "I'm going to kill you." The girl said, "No, I don't want to die. I want you to stay with me."

The boy took a knife from his pocket and stabbed her. She died in his arms. The boy was arrested and charged with first-degree murder. He was sentenced to life in prison without the possibility of parole.
